[store]
owner = "rsims55"
repo  = "football-ticket-tracker"
release_tag = "snapshots"
asset_name  = "price_snapshots.csv"

[paths]
local_csv = "data/daily/price_snapshots.csv"
archive_dir = "data/daily/archives"

[merge]
key_columns  = ["event_id", "collected_at"]
timestamp_col = "collected_at"
