name: Run Ticket Price Pipeline

on:
  workflow_dispatch:        # Allows manual runs
  schedule:
    - cron: '0 6 * * *'      # 6:00 AM UTC
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
    - cron: '0 0 * * *'
    - cron: '0 6 * * 1'
    - cron: '0 6 * * 3'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Check Python version
        run: python --version
