name: Run Ticket Price Pipeline

on:
  schedule:
    # Price Logger - 4x daily
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
    - cron: '0 0 * * *'
    # Rankings Fetcher - Monday & Wednesday at 6am
    - cron: '0 6 * * 1'
    - cron: '0 6 * * 3'
  workflow_dispatch:  # Allow manual run

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: echo "CFD_API_KEY=${{ secrets.CFD_API_KEY }}" >> $GITHUB_ENV

    - name: Run Price Logger (4x/day)
      if: |
        github.event.schedule == '0 6 * * *' ||
        github.event.schedule == '0 12 * * *' ||
        github.event.schedule == '0 18 * * *' ||
        github.event.schedule == '0 0 * * *'
      run: python src/price_logger.py

    - name: Run Rankings Fetcher (Mon/Wed 6am)
      if: |
        github.event.schedule == '0 6 * * 1' ||
        github.event.schedule == '0 6 * * 3'
      run: python src/fetchers/rankings_fetcher.py

    - name: Retrain Model Daily
      if: github.event.schedule == '0 0 * * *'
      run: python src/train_price_model.py

    - name: Evaluate Weekly Predictions and Refine
      if: github.event.schedule == '0 6 * * 1'
      run: python src/evaluate_predictions.py

    - name: Generate Weekly Report
      if: github.event.schedule == '0 6 * * 1'
      run: python src/reports/generate_weekly_report.py

    - name: Send Weekly Report Email
      if: github.event.schedule == '0 6 * * 1'
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python src/reports/send_email.py

